services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: andrew999/fitness-tracker-backend:latest
    ports:
      - "80:5000"
    networks:
      - fitness-tracker-network
    entrypoint: ["dotnet", "GymTracker.API.dll"]
   
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: andrew999/fitness-tracker-frontend:latest
    ports:
      - "8080:8080"
    networks:
      - fitness-tracker-network

networks:
  fitness-tracker-network: